### ISSUE TITLE
Establish initial setup with config.json and readme.md

### ISSUE THREAD

**Issue by macta** [exercism/pharo#15]
To try out some initial fetch scenario's we need an initial setup with a valid config file and some readme instructions to try out.

**Comment by macta** [comment]
When we get something checked in and can see how it looks, I have a feeling that some of the items in this readme need to be split out and put into other places. @kytrinyx I haven't really seen a clear recipe of what to put where - its seems a bit sprawling and almost trial and error to put the right docs in the right place. I don't mind per say - but it does make kickstarting a new track a bit trickier.

**Comment by samWson** [comment]
> Not sure who is doing merging of PR's

I'd rather not be the sole person approving/doing merges as that gives our project a [bus factor](https://en.wikipedia.org/wiki/Bus_factor) of 1 i.e. a single point of failure. @macta and @bencoman you both should be contributors by now. Do you have the ability to do merge PR's? If that is so that gives us three approvers and increases our bus factor. You've both been enthusiastically contributing so if you feel a PR meets acceptance criteria then go ahead and merge (that is if you can).

> its seems a bit sprawling and almost trial and error to put the right docs in the right place.

@macta I think Pharo is different enough from other programming languages so that we will end up with a slightly unique repo when compared with other language tracks. In the short term when lacking better guidance follow your own intuition. I think a lot of our early work will still be a draft even after merging. This is fine as we can be flexible in these early stages as we find what feels right.

**Comment by macta** [comment]
I've merged this one - but strangely the readme.md seems different than the one in the branch (possibly user error - but I'm trying to explain what happened - it seems to have lost 2 paragraphs)

**Comment by macta** [comment]
Just removed the extra H2 - I think this was just overlooked and so no merge error
